### PR TITLE
Feature/deployment

### PR DESCRIPTION
**Pull request by sdepold**

### CODE REVIEW

**Comment by neonichu** [comment]
I would rename "travis" => "ci", otherwise :ok_hand:

**Comment by johanneswuerbach** [comment]
Maybe use http://docs.travis-ci.com/user/deployment/script/ instead of manually filtering PRs and the branch?

**Comment by sdepold** [comment]
@neonichu should we add a special make target for publishing stuff through travis and/or remove the test call from the publish make target. Because if we don't we would have to run the tests twice (when using the deployment option)

**Comment by sdepold** [comment]
aka:

- Remove the test flag from publish (or create a new one)
- Add deploy hook which runs publish without the tests

**Comment by neonichu** [comment]
hm, neither sounds like a good option. Having to maintain two tasks seems cumbersome and removing the dependency could lead to publishing broken things locally (same is true for the second task as well, unless it checks for Travis). I'd rather live with a slightly longer execution time on Travis.

**Comment by sdepold** [comment]
ok. let me change the stuff

**Comment by johanneswuerbach** [comment]
Hm, why would `make test` and an added `make publish` error prone, especially when there is no need to deploy anything locally any longer?

**Comment by sdepold** [comment]
That makes sense to me. @neonichu ?

**Comment by neonichu** [comment]
¯\\\_(ツ)\_/¯ — someone is bound to execute it locally if there isn't a check, but it's not a big deal to revert anyways. So let's remove the dependency.

**Comment by sdepold** [comment]
@neonichu @johanneswuerbach PTAL

**Comment by johanneswuerbach** [comment]
LGTM, btw. is there a deploy key setup. It doesn't look like.

**Comment by sdepold** [comment]
> LGTM, btw. is there a deploy key setup? It doesn't look like.

I would add it to the env vars once this is merged

**Comment by neonichu** [comment]
LGTM :+1:

**Comment by sdepold** [comment]
so let's see :)

**Pull request merged**
