### PR TITLE
[Changed] Prepare docs before publish

### PR DESCRIPTION
**Pull request by sdepold**

### CODE REVIEW

**Comment by johanneswuerbach** [comment]
I think a better fix would have been to add `skip_cleanup: true` to the deploy section.

**Comment by sdepold** [comment]
that sounds good as well :D

**Comment by neonichu** [comment]
IMO, I think it's better that the Makefile is setup so that it doesn't rely on external factors to function.

**Comment by johanneswuerbach** [comment]
Sure, but preparing the docs twice means you could end up in publishing something you didn't tested. Also travis is running a git stash before deploy without `skip_cleanup: true`, which can cause more side-effects then just this.

**Comment by neonichu** [comment]
True, let's do both, because the generate rules are not executed again if the files are already up-to-date. Then `publish` can work on its own, but we still publish what we tested.

**Comment by neonichu** [comment]
=> #44

**Pull request merged**
