### PR TITLE
Stop markdown renderer making links in API concept doc real links.

### PR DESCRIPTION
**Pull request by ChrisChinchilla**

### CODE REVIEW

**Comment by realityking** [comment]
Good idea but why did you go for `<i>` instead of just keeping the `_` for emphasis? Just removing the `https://` should make sure they're not recognised as links anymore.

**Comment by ChrisChinchilla** [comment]
@realityking No, it seems that even those get turned into links. I don't remember that happening before, so I'm slightly confused, It seems to be GFM vs plain Markdown discrepancy too. I may revisit properly later and see if there's a 'better'way.

**Comment by realityking** [comment]
That's weird. Just for future reference, the website is using kramdown as parser. Unfortunately it is its own special snowflake.

**Comment by ChrisChinchilla** [comment]
@realityking Indeed, Markdown is so simple! ;)

**Pull request merged**
