### PR TITLE
Consistently use auth via query param for CDA

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by sdepold** [comment]
Shouldn't this change happen in the CMA docs too?

**Comment by neonichu** [comment]
Eventually, yes, but currently not possible => #37

**Comment by sdepold** [comment]
So we are using a header which we are overwriting with the environment variable?

**Comment by neonichu** [comment]
Yah, it's the only way I see to get the dredd tests working right now

**Comment by sdepold** [comment]
ok

**Pull request merged**
