### PR TITLE
Return the CMA tests to a working state.

### PR DESCRIPTION
**Pull request by realityking**
This is pretty much the minimum necessary to make them working again + fixing some minor errors found along the way.

Reviews: @neonichu @sdepold

### CODE REVIEW

**Comment by sdepold** [comment]
:ok_hand:

**Comment by neonichu** [comment]
LGTM, should be merge-able once :green_heart:

**Comment by realityking** [comment]
:tada:

**Comment by neonichu** [comment]
MAKE TESTS GREAT AGAIN!

**Pull request merged**
